CREATE TABLE IF NOT EXISTS alert_logs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  event_id VARCHAR(64) NOT NULL UNIQUE,
  host_id VARCHAR(64),
  user_id VARCHAR(64),
  file_path VARCHAR(512),
  file_hash VARCHAR(128),
  `sensitive` BOOLEAN DEFAULT FALSE,
  sensitive_type VARCHAR(128),
  risk_level ENUM('critical','high','medium','low','info'),
  old_risk_level ENUM('critical','high','medium','low','info'),
  process_name VARCHAR(256),
  process_path VARCHAR(512),
  target VARCHAR(512),
  operation VARCHAR(64),
  sensitive_file_id VARCHAR(64),
  is_merge_event BOOLEAN DEFAULT FALSE,
  file_count INT DEFAULT 1,
  files_json JSON,
  false_positive_reason TEXT,
  agent_verdict ENUM('false_positive','true_alert','uncertain'),
  agent_confidence DECIMAL(4,3),
  agent_explanation TEXT,
  recall_score DECIMAL(4,3) DEFAULT 0,
  timestamp BIGINT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_timestamp (timestamp),
  INDEX idx_user (user_id),
  INDEX idx_risk (risk_level),
  INDEX idx_agent_verdict (agent_verdict),
  INDEX idx_created (created_at)
);

CREATE TABLE IF NOT EXISTS whitelist_rules (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  rule_name VARCHAR(256) NOT NULL,
  logic ENUM('AND','OR') DEFAULT 'OR',
  process_name VARCHAR(256),
  user_id VARCHAR(64),
  file_path_pattern VARCHAR(512),
  time_window_start TIME,
  time_window_end TIME,
  enabled BOOLEAN DEFAULT TRUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS false_positive_library (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  scenario_key VARCHAR(512) NOT NULL UNIQUE,
  host_id VARCHAR(64),
  user_id VARCHAR(64),
  sensitive_type VARCHAR(128),
  risk_level VARCHAR(32),
  process_name VARCHAR(256),
  process_path VARCHAR(512),
  target VARCHAR(512),
  operation VARCHAR(64),
  reason TEXT,
  embedding_json LONGTEXT,
  hit_count INT DEFAULT 1,
  last_seen_at DATETIME,
  expired_at DATETIME NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_expired (expired_at),
  INDEX idx_user (user_id),
  INDEX idx_process (process_name),
  INDEX idx_last_seen (last_seen_at)
);
